name: intro-to-cs
channels:
- anaconda
- conda-forge
dependencies:
- ipykernel=6.9.1
- jupyter=1.0.0
- jupyter_contrib_nbextensions=0.5.1
- jupyterlab=3.4.3
- matplotlib=3.5.2
- pandas-profiling=3.2.0
- python=3.9.7
- seaborn=0.11.2
- plotly=5.9.0
- scikit-learn=1.1.1
